### ISSUE TITLE
Incomplete Options | Find-CouchDBDocuments

### ISSUE THREAD

**Issue by thefunc5** [MatteoGuadrini/PSCouchDB#1]
This Cmdlet does not provide the full functionality available. Below link provides detail on the many other fields that would be amazing to have as part of the Cmdlet.

http://docs.couchdb.org/en/2.1.1/api/database/find.html?highlight=find

**Comment by thefunc5** [comment]
Add below?
```
param([int] $Limit)

    if ($Limit) {
        $Data += ",`"limit`": [int]$Limit"
    }

```

**Comment by thefunc5** [comment]
Closing as this can be  inadvertently resolved through exporting Send-CouchDBRequest issue #4
--

**Comment by MatteoGuadrini** [comment]
Hi thefunc5,
You had perfectly reason! For the my less time or other situations, I implemented only necessary _find option for my personal project. In version 1.6.0, I will implement all functionality of _find document and I rewrite Find cmdlet with native pscustomobject and convert to json only at the least of find operation. $Value is string because powershell cast an integer or other type automatically, if is possible. Anyway, I consider your proposal and I will assess.
Regards
