### ISSUE TITLE
Value converted to string | Find-CouchDBDocuments

### ISSUE THREAD

**Issue by thefunc5** [MatteoGuadrini/PSCouchDB#3]
$Value parameter is _always_ converted to string. This appears to be by design, however, it's particularly painful if your documents contain numbers or bools.

**Comment by thefunc5** [comment]
Played with this a bit. Maybe another Switch Statement like below?
(obviously this is dirty code and needs more types)
```
    switch ($Value.GetType().Name) {
        Boolean {$Value = ($Value.ToString()).ToLower()}
        String {$Value = "`"$Value`""}
        Double {$Value = $Value}
        Int32 {$Value = $Value}
    }
```
You would then change your switch ($Operator) to fit this : 
```
    switch ($Operator) {
        'lt'        { $Data += '"$lt":' ;       if ($Selector -and $Value) { $Data += $Value } }
    }
```

and your final $Data += '}' could be updated to
`$Data += '}}}' `

I'm a noob, so if I'm in the wrong, let me know!

**Comment by thefunc5** [comment]
Closing as this can be  inadvertently resolved through exporting Send-CouchDBRequest issue #4

**Comment by MatteoGuadrini** [comment]
Simple is better than complex. Export Send-CouchDBRequest? Would add complex in the final user because this write the entire request with entire data and your json complexity before send on the Couchdb database. I prefer your suggestions like implement other functionality parameters for this cmdlet and make more and more simple.
I hope being helpful. 
Regards
